### ISSUE TITLE
Clarify "Its possible that some of the modules are actually up-to-date."

### ISSUE THREAD

**Issue by nathanabercrombie** [braydie/HowToBeAProgrammer#3]
in 3-Advanced/Technical-Judgement/03-Choosing Languages.md
the phrase "Its possible that some of the modules are actually up-to-date." is very vague.  Isn't it always possible they are up to date? What does language have to do with it?

**Comment by RobertLRead** [comment]
You are right @nathanabercrombie. I don't even remember what I meant---perhaps I was trying to be sarcastic.

I recommend changing it to: "It is a lower energy-barrier to update individual modules, and therefore easier to keep the whole system up-to-date."

**Comment by braydie** [comment]
Sorry to play devil's advocate @RobertLRead, but I don't understand how that is a benefit of choosing a language?

I wonder whether it is worth including something around each programming language having its own strengths and weaknesses?

**Comment by RobertLRead** [comment]
@braydie Well my point is not that multiple languages per se is a benefit, but that having a loosely-coupled system in which you can upgrade individual components is a benefit. If you have such a system, then you can choose the languages of each module appropriately with little cost.

In contrast, a mandate from above such as "The whole system will be written in Java" tends to be self-defeating. It is an attempt to make workers fungible, but has the side effect of preventing advancement of individual modules by limiting them to a single language. Over time, the one-language system tends to become a legacy system that is not upgraded, because when the base language becomes out-of-date, the whole system must be rewritten as a block, rather than on a component-by-component basis.

**Comment by braydie** [comment]
Makes sense - do you think then that the last point could be changed to something along the lines of "one language may not be a good fit for the overall system - having multiple languages for your modules allows you to pick the right tool for the job"

**Comment by braydie** [comment]
Interesting how this could lead nicely into a discussion around modularity within a system! :smile:

**Comment by RobertLRead** [comment]
@braydie I like your wording very much.  I was searching for that (though I am not giving this my full attention at present.)

**Comment by braydie** [comment]
Is this issue ok to close now @nathanabercrombie?

**Comment by nathanabercrombie** [comment]
Yup
