### ISSUE TITLE
touch typing an intermediate skill?

### ISSUE THREAD

**Issue by sindhus** [braydie/HowToBeAProgrammer#49]
I was wondering why [touch typing has been put in intermediate chapter](https://github.com/braydie/HowToBeAProgrammer/blob/master/2-Intermediate/Personal-Skills/07-Learn%20to%20Type.md
). It's almost indispensible to be a touch typer regardless of whether you are a programmer or not. I have enough programming and interpersonal things to navigate as a newbie programmer, if touch typing was one of them then it would add to my burden.

**Comment by GuillaumeLeclerc** [comment]
I think the point is, when you are a beginner, you spend more time thinking about what to type. correcting small syntax errors (and sometimes even copy/pasting code).

Learning touch typing would be the same as optimizing a part of your program that only takes 1% of the global run time.

**Comment by braydie** [comment]
I agree with you @GuillaumeLeclerc, becoming a efficient typist is something that comes with time - as a beginner you would want to focus on typing the *right* thing more so than typing something quickly. You do have a point though @sindhus, being a decent typist does help massively to reduce the amount of stress you are likely to encounter as you're learning!

**Comment by RobertLRead** [comment]
Yes, the commentors have echoed my thoughts.  If you come to this essay as a beginner, you should work on learning touch-typing, but it should not be your highest priority. If you are an intermediate programmer and you don't know how to touch type, you should drop what you are doing and train yourself in that way.

It would be best if everyone knew typing before they beginning programming, but I don't think we should insist upon that, because even young kids should begin coding.

**Comment by Bilge** [comment]
I believe this can be closed since the majority agree touch typing is not needed as a beginner. A good programmer spends the majority of their time thinking, not typing. On the contrary, it is often a bad programmer whom spends most of their time typing because they're invariably creating technical debt and doing more harm than good.

**Comment by braydie** [comment]
hey @Bilge
