### ISSUE TITLE
Language that welcomes both women and men?

### ISSUE THREAD

**Issue by roybahat** [braydie/HowToBeAProgrammer#68]
In the intermittent bugs chapter, the name you called the tool you used -- the French stripper -- looks like an example of the kind of thing that, while it seems intended innocuously, could alienate women. This is otherwise an amazing introductory text, and our industry has a real problem with welcoming both women and men. Consider changing?

**Comment by Jiehong** [comment]
There are men & women strippers as far as I know. It sounded masculine to me when I read it…

**Comment by anselmbradford** [comment]
Run through https://github.com/amperser/proselint

**Comment by braydie** [comment]
Unsure about the French stripper - I read it is a joke in the context of stripping HTML - I didn't even apply a gender to it! :smile: I'm keen to get some more feedback on this particular instance before changing it I think, though.

I'd be interested to see what proselint would turn up for the book.

**Comment by smuuf** [comment]
Are you sure you're not fighting a problem nobody sane needs you to fight; or even: fighting a problem nobody sane considers a problem, Roy?

**Comment by roybahat** [comment]
@bradie I asked some (sane) colleagues of both genders and all had the same reaction I did. I read it as a joke, too -- the question is whether the value of the joke is worth potentially alienating half the population. Technically, of course it could be read without gender -- in practice, I doubt that would be the case. Feels to me like, as a profession, we want to err on the side of avoiding unnecessary insult.

**Comment by Xerlith** [comment]
Pretty sure this is not an issue. There are male strippers also. The joke is light-hearted and there is no sense of giving it the attention you demand.

**Comment by roybahat** [comment]
Curious for those of you who feel it isn't an issue, is there any piece of evidence -- expert opinion, statistic, or personal experience from someone -- that might lead you to change your mind?

**Comment by RobertLRead** [comment]
I'm generally in favor of leaving it the way I wrote it.  The firm really DID call it the French stripper, I didn't make that up. I have been at pains (and booed by some) for use the feminine pronoun in equal parts in examples.  I don't think the mention of strippers is offensive to women; women have heard of them and know that they exist.

**Comment by ginatrapani** [comment]
Hi! I'm a programmer, the author of several bestselling books on technology, someone who cares deeply about inclusive language, and someone who has had to modify my own word choices when [a caring reader suggested](https://github.com/ginatrapani/narrowthegapp/pull/2) they could offend a segment of my readers.

First, I want to thank you for publishing a useful resource under a permissive license. That's a service to the community, and I'm grateful to you for it.

That said, I did want to weigh in on Roy's ticket here. Let's review the facts:

* The firm built software in France that strips HTML tags.
* Calling it "the French stripper" is a joke, and no one meant any harm by it.
* It is a joke precisely because of the double entendre, the reference to human strippers.
* Statistically, female strippers are far more common than male strippers.
* For many readers, using the phrase "French stripper" will invoke an image of a woman performing for a male audience in a sexual way.
* You're writing about _software_, so even if the firm actually did call it that, and meant no harm, a sexual reference is wholly unnecessary to make your point.

Now I will share an opinion. To me, this phrasing screams "written by a brogrammer." It very subtly suggests programming is a man's world. This is not a joke I would share with my daughter while she was learning how to be a programmer.

Do you want to take that risk? Is the joke really worth it? All I ask is that you consider these questions.

**Comment by Xerlith** [comment]
That's a long way to use an argument that is purely eristic. 
It operates on a presumption, dressed up as a fact, that 

> for many readers, using the phrase "French stripper" will invoke an image of a woman performing for a male audience in a sexual way.

, but there is no way for you to back this claim. If we're going purely by anecdotal proof, my good friend, a programmer, said her first thought was the two gay male strippers she heard about in our hometown. 

This is far from a fact, and more of a reach.

**Comment by ahangchen** [comment]
Actually, many libraries to strip html tags from text call themselves stripper, in documents, in code.  
What the libraries do is stripping, so we call them strippers. Is there a name more suitable? 
If you think this name is not good,  any alternatives for it? @roybahat

**Comment by roybahat** [comment]
I submitted a pull request @ahangchen with my attempt to write around it. (I'm not one to ask questions without trying to help solve the issue.) I'll leave it at this, and let @RobertLRead and @braydie decide what they want to do here. 

I want to emphasize that I thought this book was wonderful, and that's the only reason I cared to try to remove the one spot in it that I thought might unintentionally alienate people we want to attract to this profession. Why take the risk of that... and I agree with @ginatrapani that I'd avoid sharing this joke with my daughter, too. I'd rather she be able to learn to be a programmer without worrying about microaggressions.

**Comment by braydie** [comment]
@roybahat, I really appreciate the time you've taken with this issue - I've really enjoyed seeing this discussion and I've loved that although there are many differing opinions on the 'french stripper', people have stayed civil and the conversation has remained constructive throughout. 

This issue is a perfect example of why I felt putting the guide onto github was a good idea - to build a community around these ideas to help share and improve this guide (and help some programmers too! :smile:)

I'm happy with the change you've made as I don't think it takes away from the point of the example and  helps us be a bit more inclusive. You're absolutely right in that we don't want to alienate anyone - this is  another reason for sharing this guide with as many people as possible (and in as many languages as possible too!)

Thanks again!
